### ISSUE TITLE
Bug when calling localStorage.clear()

### ISSUE THREAD

**Issue by kesne** [nodeca/tabex#10]
When the clear method is called, the corresponding StorageEvent has a key property set to `null`. 
See here: https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent

This causes an exception to be thrown at this line because it attempts to call `indexOf` on null:
https://github.com/nodeca/tabex/blob/93feb7d020b8294d09af1c8ed862059fb6b5259e/lib/router.js#L310

**Comment by puzrin** [comment]
Do you mean direct `.clear()` call from external code?

**Comment by jimrhoskins** [comment]
Yes, `localStorage.clear()` will cause this error. Also clearing Local Storage via the chrome content settings will also cause this error.

**Comment by puzrin** [comment]
Good catch, thanks for report!

Is it urgent or can wait 2 weeks?

**Comment by kesne** [comment]
@puzrin No worries, it can totally wait a few weeks.

**Comment by kesne** [comment]
@puzrin Any updates on this? Sadly we've had this error keep showing up in production.

**Comment by puzrin** [comment]
Marked to fix tomorrow

**Comment by puzrin** [comment]
Could you check files from master for sure prior i do release?

**Comment by puzrin** [comment]
Published 1.0.5 with fix
