### ISSUE TITLE
One WebSocket between tabs

### ISSUE THREAD

**Issue by Shkarbatov** [nodeca/tabex#11]
Hi, trying to understand:

```
Share single websocket connection when multiple tabs open (save server resources).
```

Maybe You have any examples, how to do this?
I know how to check SharedWorker count, but how I can be shure, that only one WebSocket used?
As I understand, after page refresh - SharedWorker recreate anew one, and called new WebSocket().

Thanks!

**Comment by puzrin** [comment]
See example with faye in readme. You can replace faye with something else.

Each tab can create it's own connection, but only one is activated at once. Other tabs route messates master (tab with connection)

There are no SharedWorkers here.
