### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nicola-spb** [nodeca/tabex#22]
Hello,
If you open your demo http://nodeca.github.io/tabex/ and open More tools -> Task Manager in chrome then you will see increasing js memory every second  (+1 Kb).

**Comment by puzrin** [comment]
IMO that's not enough for proof. GC may free memory in bulks and it's logic depends on available memory.

What happens with memory after 1 day?

**Comment by nicola-spb** [comment]
Ok. Is it true. After manual clear GC memory is recovered.
Sorry.
